jobs:
  include:
    - stage: Tests
      name: Kuzzle GraphQL Plugin Tests
      language: node_js
      node_js: 12
      cache:
        directories:
          - ~/.npm
          - ~/.cache
          - node_modules

      install:
        - npm install --silent --unsafe-perm

      script:
        - bash features/run-kuzzle-stack.sh
        - npm test
